
import { Product } from "@/lib/types";
import Features from "../components/Features";
import PageHeader from "../components/PageHeader";
import Pagination from "../components/Pagination";
import ProductCard from "../components/ProductCard";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Shop | NextCart",
  description: "Generated by create next app",
};

const ShopPage = async () => {
  const baseURL = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
  const response = await fetch(`${baseURL}/api/products`, {
    cache: "no-store",
  });
  const products = await response.json();

  return (
    <div>
      <PageHeader title="Shop" />

      <section className="wrapper">
        <div className="grid lg:grid-cols-4 md:grid-cols-2 sm:grid-cols-2 grid-cols-1 gap-6 mt-8">
          {products.map((product: Product) => (
            <ProductCard key={product._id} product={product} />
          ))}
        </div>

        <Pagination />
      </section>

      <Features />
    </div>
  );
};

export default ShopPage;
